import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  es: { translation: {
    app: { brand: "Bioma", greeting: "Hola, {{name}}", changeLanguage: "English" }, common: { loading: "Cargando…", select: "Selecciona una opción", retry: "Reintentar" }, errors: { network: "No fue posible conectar con el servicio." },
    login: { brandCopy: "Registro y análisis seguro de fauna silvestre.", eyebrow: "Fundación Yarumo", title: "Bienvenida a Bioma", subtitle: "Ingresa con tu cuenta de investigación.", email: "Correo electrónico", password: "Contraseña", submit: "Iniciar sesión" },
    nav: { label: "Navegación principal", menu: "Abrir menú", dashboard: "Inicio", sightings: "Avistamientos", species: "Especies", sites: "Sitios", researchers: "Investigadores", search: "Búsqueda", copilot: "Copiloto IA", reports: "Reportes", profile: "Configuración" },
    views: { dashboard: { title: "Resumen de actividad" }, sightings: { title: "Avistamientos" }, species: { title: "Especies" }, sites: { title: "Sitios monitoreados" }, researchers: { title: "Investigadores" }, search: { title: "Búsqueda de avistamientos" }, copilot: { title: "Copiloto de campo" }, reports: { title: "Reportes" }, profile: { title: "Configuración" } },
    dashboard: { subtitle: "Actividad y avistamientos autorizados para tu nivel de acreditación.", error: "No fue posible cargar el resumen.", metrics: { sightings: "Avistamientos", species: "Especies registradas", sites: "Sitios monitoreados", notes: "Notas de campo" }, classificationTitle: "Avistamientos por clasificación", classificationSubtitle: "Distribución visible para ti", total: "Total", activityTitle: "Actividad reciente", activitySubtitle: "Cambios registrados en el historial", activityEmpty: "No hay actividad reciente.", activity: { created: "registró un avistamiento de", edited: "editó un avistamiento de", voided: "anuló un avistamiento de" } },
    catalog: { eyebrow: "Catálogo científico", speciesTitle: "Especies registradas", sitesTitle: "Sitios monitoreados", researchersTitle: "Investigadores activos", photoCredit: "Foto: {{attribution}} · {{license}}", error: "No fue posible cargar esta información." },
    reports: { eyebrow: "Análisis autorizado", title: "Reportes", description: "Resumen de los registros que puedes consultar según tu acreditación.", error: "No fue posible cargar el reporte." },
    sightings: { eyebrow: "Historial de campo", title: "Avistamientos recientes", new: "Registrar", search: "Buscar en notas de campo…", allSpecies: "Todas las especies", allSites: "Todos los sitios", empty: "No hay avistamientos disponibles.", loadMore: "Cargar más", void: "Anular avistamiento", voidReason: "Anulación solicitada desde la interfaz", formTitle: "Nuevo avistamiento", reference: "Referencia", species: "Especie", site: "Sitio", observedAt: "Fecha y hora", latitude: "Latitud", longitude: "Longitud", classification: "Clasificación", notes: "Notas de campo", submit: "Guardar avistamiento", pending: "Enviando…" },
    classification: { public: "Público", restricted: "Restringido", confidential: "Confidencial" },
    copilot: { title: "Copiloto IA", subtitle: "Consulta solo el historial autorizado.", question: "Pregunta para el copiloto", placeholder: "Pregunta por observaciones, especies o notas de campo…", ask: "Consultar", thinking: "Consultando…", sources: "Fuentes autorizadas" },
    profile: { title: "Perfil de investigación", signedIn: "Sesión activa", level: "Nivel {{level}}", logout: "Cerrar sesión" },
  } },
  en: { translation: {
    app: { brand: "Bioma", greeting: "Hello, {{name}}", changeLanguage: "Español" }, common: { loading: "Loading…", select: "Select an option", retry: "Retry" }, errors: { network: "The service could not be reached." },
    login: { brandCopy: "Secure wildlife monitoring and analysis.", eyebrow: "Yarumo Foundation", title: "Welcome to Bioma", subtitle: "Sign in with your research account.", email: "Email address", password: "Password", submit: "Sign in" },
    nav: { label: "Main navigation", menu: "Open menu", dashboard: "Home", sightings: "Sightings", species: "Species", sites: "Sites", researchers: "Researchers", search: "Search", copilot: "AI Copilot", reports: "Reports", profile: "Settings" },
    views: { dashboard: { title: "Activity summary" }, sightings: { title: "Sightings" }, species: { title: "Species" }, sites: { title: "Monitored sites" }, researchers: { title: "Researchers" }, search: { title: "Search sightings" }, copilot: { title: "Field copilot" }, reports: { title: "Reports" }, profile: { title: "Settings" } },
    dashboard: { subtitle: "Activity and sightings authorized for your accreditation level.", error: "The summary could not be loaded.", metrics: { sightings: "Sightings", species: "Registered species", sites: "Monitored sites", notes: "Field notes" }, classificationTitle: "Sightings by classification", classificationSubtitle: "Distribution visible to you", total: "Total", activityTitle: "Recent activity", activitySubtitle: "Changes recorded in history", activityEmpty: "There is no recent activity.", activity: { created: "registered a sighting of", edited: "edited a sighting of", voided: "voided a sighting of" } },
    catalog: { eyebrow: "Scientific catalogue", speciesTitle: "Registered species", sitesTitle: "Monitored sites", researchersTitle: "Active researchers", photoCredit: "Photo: {{attribution}} · {{license}}", error: "This information could not be loaded." },
    reports: { eyebrow: "Authorized analysis", title: "Reports", description: "Summary of the records you can query at your accreditation level.", error: "The report could not be loaded." },
    sightings: { eyebrow: "Field history", title: "Recent sightings", new: "Register", search: "Search field notes…", allSpecies: "All species", allSites: "All sites", empty: "No sightings are available.", loadMore: "Load more", void: "Void sighting", voidReason: "Void requested from the interface", formTitle: "New sighting", reference: "Reference", species: "Species", site: "Site", observedAt: "Date and time", latitude: "Latitude", longitude: "Longitude", classification: "Classification", notes: "Field notes", submit: "Save sighting", pending: "Sending…" },
    classification: { public: "Public", restricted: "Restricted", confidential: "Confidential" },
    copilot: { title: "AI Copilot", subtitle: "Query authorized field history only.", question: "Question for the copilot", placeholder: "Ask about observations, species, or field notes…", ask: "Ask", thinking: "Thinking…", sources: "Authorized sources" },
    profile: { title: "Research profile", signedIn: "Signed in", level: "Level {{level}}", logout: "Sign out" },
  } },
};

void i18n.use(initReactI18next).init({ resources, lng: "es", fallbackLng: "es", interpolation: { escapeValue: false } });
export default i18n;
