import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  es: { translation: {
    app: { brand: "Bioma", greeting: "Hola, {{name}}", changeLanguage: "English" }, common: { loading: "Cargando…", select: "Selecciona una opción", retry: "Reintentar", close: "Cerrar", cancel: "Cancelar" }, errors: { network: "No fue posible conectar con el servicio." },

    login: { brandCopy: "Registro y análisis seguro de fauna silvestre.", eyebrow: "Fundación Yarumo", title: "Bienvenido a Bioma", subtitle: "Ingresa con tu cuenta de investigación.", email: "Correo electrónico", password: "Contraseña", submit: "Iniciar sesión" },
    nav: { label: "Navegación principal", menu: "Abrir menú", dashboard: "Inicio", sightings: "Avistamientos", species: "Especies", sites: "Sitios", researchers: "Investigadores", search: "Búsqueda", chat: "Mensajes", copilot: "Copiloto IA", reports: "Reportes", profile: "Configuración", admin: "Administración" },
    views: { dashboard: { title: "Resumen de actividad" }, sightings: { title: "Avistamientos" }, species: { title: "Especies" }, sites: { title: "Sitios monitoreados" }, researchers: { title: "Investigadores" }, search: { title: "Búsqueda de avistamientos" }, chat: { title: "Mensajes" }, copilot: { title: "Copiloto de campo" }, reports: { title: "Reportes" }, profile: { title: "Configuración" }, admin: { title: "Administración" } },
    dashboard: { subtitle: "Actividad y avistamientos autorizados para tu nivel de acreditación.", error: "No fue posible cargar el resumen.", metrics: { sightings: "Avistamientos", species: "Especies registradas", sites: "Sitios monitoreados", notes: "Notas de campo" }, classificationTitle: "Avistamientos por clasificación", classificationSubtitle: "Distribución visible para ti", total: "Total", activityTitle: "Actividad reciente", activitySubtitle: "Cambios registrados en el historial", activityEmpty: "No hay actividad reciente.", activity: { created: "registró un avistamiento de", edited: "editó un avistamiento de", voided: "anuló un avistamiento de" } },
    catalog: { eyebrow: "Catálogo científico", speciesTitle: "Especies registradas", sitesTitle: "Sitios monitoreados", researchersTitle: "Investigadores activos", siteLabel: "Sitio de monitoreo", siteImageFallback: "Sin imagen curada para {{site}}", photoCredit: "Foto: {{attribution}} · {{license}}", error: "No fue posible cargar esta información.", viewDetails: "Ver ficha completa", speciesProfile: "Ficha Biológica", siteProfile: "Ficha de Sitio Monitoreado", description: "Descripción y Comportamiento", habitat: "Hábitat y Rango Altitudinal", diet: "Dieta y Rol Ecológico", conservation: "Estado de Conservación", ecosystem: "Bioma / Ecosistema", region: "Región Geográfica", siteDescription: "Descripción del Área Protegida", close: "Cerrar ficha", unspecified: "No especificado" },
    reports: { eyebrow: "Análisis autorizado", title: "Reportes", description: "Resumen de los registros que puedes consultar según tu acreditación.", classificationLabel: "Distribución de avistamientos por clasificación", error: "No fue posible cargar el reporte." },
    sightings: { eyebrow: "Historial de campo", title: "Avistamientos recientes", viewAll: "Ver todos", open: "Abrir avistamiento de {{species}}", new: "Registrar", search: "Buscar en notas de campo…", allSpecies: "Todas las especies", allSites: "Todos los sitios", empty: "No hay avistamientos disponibles.", loadMore: "Cargar más", void: "Anular avistamiento", voidReason: "Anulación solicitada desde la interfaz", confirmVoidTitle: "Confirmar anulación de avistamiento", confirmVoidMessage: "¿Estás seguro de anular el avistamiento de {{species}} ({{reference}}) en {{site}}? Esta acción quedará registrada en la auditoría científica.", confirmVoidButton: "Anular registro", notOwner: "Solo el investigador autor puede anular este registro", formTitle: "Nuevo avistamiento", reference: "Referencia", species: "Especie", site: "Sitio", observedAt: "Fecha y hora", latitude: "Latitud", longitude: "Longitud", classification: "Clasificación", notes: "Notas de campo", submit: "Guardar avistamiento", pending: "Enviando…", detailTitle: "Detalle del avistamiento", detailError: "No fue posible abrir este avistamiento.", detail: { reference: "Referencia", site: "Sitio", observedAt: "Fecha de observación", researcher: "Investigador", notes: "Notas de campo", coordinates: "Coordenadas exactas" } },
    classification: { public: "Público", restricted: "Restringido", confidential: "Confidencial" },
    copilot: { eyebrow: "Guía de campo", title: "Copiloto IA", subtitle: "Consulta solo el historial autorizado.", question: "Pregunta para el copiloto", placeholder: "Pregunta por observaciones, especies o notas de campo…", ask: "Enviar", thinking: "Consultando…", sources: "Fuentes autorizadas", welcome: "Estoy aquí para explorar tu historial de campo.", welcomeHint: "Haré respuestas basadas únicamente en registros que tengas autorización de consultar.", enterHint: "Enter para enviar · Shift + Enter para una nueva línea", usageTitle: "Uso de esta sesión", usageSubtitle: "Resumen de actividad y consultas en esta sesión", usageQueries: "consultas", usageQueriesHint: "Preguntas realizadas", usageTokens: "tokens procesados", usageTokensHint: "Volumen de procesamiento", usageLastQuery: "última consulta", usageLastQueryHint: "Última respuesta recibida", usageSecurityNotice: "Las respuestas se generan exclusivamente a partir de los registros autorizados para tu nivel de acreditación.", usageEmpty: "Aún no hay consultas registradas.", usageUnavailable: "No fue posible consultar el uso.", newConversation: "Nueva consulta", conversations: "Historial de hilos", deleteConversation: "Eliminar hilo", confirmDeleteTitle: "¿Eliminar conversación?", confirmDeleteMessage: "¿Deseas eliminar el hilo \"{{title}}\"? Se archivará de tu historial de consultas.", confirmDeleteButton: "Eliminar", noConversations: "Sin consultas previas" },
    chat: { sidebarTitle: "Comunicaciones", searchPlaceholder: "Buscar investigador o canal…", researchers: "Investigadores", channels: "Canales de campo", emptyChannels: "Sin canales activos", selectPrompt: "Selecciona una conversación", selectPromptDesc: "Elige un investigador o canal para enviar mensajes seguros o invocar a @copilot.", placeholder: "Escribe un mensaje o usa @copilot para consultar…", enterHint: "Enter para enviar · Shift + Enter para salto de línea", copilotHint: "Menciona @copilot para consultar avistamientos autorizados.", protectedChannel: "Canal seguro y confidencial", usageTitle: "Consumo de Copiloto en Chat", usageSubtitle: "Métricas acumuladas de procesamiento RAG y tokens", queries: "consultas acumuladas", queriesHint: "Preguntas procesadas por el copiloto", tokens: "tokens consumidos", tokensHint: "Volumen total de entrada y salida", lastQuery: "última respuesta", lastQueryHint: "Momento de última interacción", securityNotice: "El copiloto solo responde con avistamientos y notas autorizadas para todos los miembros del canal.", createGroup: "Crear grupo", createGroupTitle: "Nuevo Grupo de Investigación", createGroupSubtitle: "Crea un espacio de trabajo colaborativo para compartir avistamientos y consultar con @copilot.", groupName: "Nombre del grupo", groupNamePlaceholder: "Ej. Expedición Sierra Nevada", selectMembers: "Seleccionar investigadores", membersCount: "{{count}} seleccionados", createGroupSubmit: "Crear Grupo", groupMemberCount: "{{count}} investigadores", minMembersHint: "Selecciona al menos un colega para el grupo.", viewMembers: "Ver integrantes", messageOptions: "Opciones de mensaje", editMessage: "Editar", deleteMessage: "Eliminar", deletedMessage: "Este mensaje fue eliminado", editedMessage: "Mensaje editado", authorizedSources: "Fuentes autorizadas", accessLevel: "Nivel de acceso", groupMembersTitle: "Integrantes del grupo", activeResearchers: "{{count}} investigadores activos", searchColleague: "Buscar colega por nombre o cargo…", selectResearcher: "Seleccionar {{name}}", level: "Nivel {{level}}", copilotName: "Copiloto Bioma", addMembers: "Agregar integrantes", leaveGroup: "Salir del grupo", leaveGroupConfirm: "¿Seguro que quieres salir de este grupo? Ya no podrás ver sus mensajes." },
    profile: { title: "Perfil de investigación", signedIn: "Sesión activa", level: "Nivel {{level}}", logout: "Cerrar sesión", adminDescription: "Gestiona el system prompt y su historial de versiones.", openAdmin: "Administrar prompts" },
    adminPrompts: { restrictedTitle: "Administración restringida", restrictedDescription: "Solo una cuenta administradora puede gestionar las versiones del prompt.", title: "Prompts del copiloto", description: "Crear una versión la activa; puedes volver a una versión anterior sin perder trazabilidad.", scope: "Ámbito", field: "Copiloto de campo", chat: "Copiloto en mensajes", greeting: "Saludos", placeholder: "Escribe una nueva versión…", save: "Guardar y activar versión", history: "Historial verificable", active: "Activa", createdBy: "Creada por {{name}}", restore: "Restaurar" },
  } },
  en: { translation: {
    app: { brand: "Bioma", greeting: "Hello, {{name}}", changeLanguage: "Español" }, common: { loading: "Loading…", select: "Select an option", retry: "Retry", close: "Close", cancel: "Cancel" }, errors: { network: "The service could not be reached." },

    login: { brandCopy: "Secure wildlife monitoring and analysis.", eyebrow: "Yarumo Foundation", title: "Welcome to Bioma", subtitle: "Sign in with your research account.", email: "Email address", password: "Password", submit: "Sign in" },
    nav: { label: "Main navigation", menu: "Open menu", dashboard: "Home", sightings: "Sightings", species: "Species", sites: "Sites", researchers: "Researchers", search: "Search", chat: "Messages", copilot: "AI Copilot", reports: "Reports", profile: "Settings", admin: "Administration" },
    views: { dashboard: { title: "Activity summary" }, sightings: { title: "Sightings" }, species: { title: "Species" }, sites: { title: "Monitored sites" }, researchers: { title: "Researchers" }, search: { title: "Search sightings" }, chat: { title: "Messages" }, copilot: { title: "Field copilot" }, reports: { title: "Reports" }, profile: { title: "Settings" }, admin: { title: "Administration" } },
    dashboard: { subtitle: "Activity and sightings authorized for your accreditation level.", error: "The summary could not be loaded.", metrics: { sightings: "Sightings", species: "Registered species", sites: "Monitored sites", notes: "Field notes" }, classificationTitle: "Sightings by classification", classificationSubtitle: "Distribution visible to you", total: "Total", activityTitle: "Recent activity", activitySubtitle: "Changes recorded in history", activityEmpty: "There is no recent activity.", activity: { created: "registered a sighting of", edited: "edited a sighting of", voided: "voided a sighting of" } },
    catalog: { eyebrow: "Scientific catalogue", speciesTitle: "Registered species", sitesTitle: "Monitored sites", researchersTitle: "Active researchers", siteLabel: "Monitoring site", siteImageFallback: "No curated image for {{site}}", photoCredit: "Photo: {{attribution}} · {{license}}", error: "This information could not be loaded.", viewDetails: "View full profile", speciesProfile: "Biological Profile", siteProfile: "Monitored Area Profile", description: "Description & Behavior", habitat: "Habitat & Elevation Range", diet: "Diet & Ecological Role", conservation: "Conservation Status", ecosystem: "Biome / Ecosystem", region: "Geographic Region", siteDescription: "Protected Area Description", close: "Close profile", unspecified: "Not specified" },

    reports: { eyebrow: "Authorized analysis", title: "Reports", description: "Summary of the records you can query at your accreditation level.", classificationLabel: "Sighting distribution by classification", error: "The report could not be loaded." },
    sightings: { eyebrow: "Field history", title: "Recent sightings", viewAll: "View all", open: "Open {{species}} sighting", new: "Register", search: "Search field notes…", allSpecies: "All species", allSites: "All sites", empty: "No sightings are available.", loadMore: "Load more", void: "Void sighting", voidReason: "Void requested from the interface", confirmVoidTitle: "Confirm sighting void", confirmVoidMessage: "Are you sure you want to void the sighting of {{species}} ({{reference}}) at {{site}}? This action will be recorded in the scientific audit.", confirmVoidButton: "Void record", notOwner: "Only the authoring researcher can void this record", formTitle: "New sighting", reference: "Reference", species: "Species", site: "Site", observedAt: "Date and time", latitude: "Latitude", longitude: "Longitude", classification: "Classification", notes: "Field notes", submit: "Save sighting", pending: "Sending…", detailTitle: "Sighting detail", detailError: "This sighting could not be opened.", detail: { reference: "Reference", site: "Site", observedAt: "Observation date", researcher: "Researcher", notes: "Field notes", coordinates: "Exact coordinates" } },
    classification: { public: "Public", restricted: "Restricted", confidential: "Confidential" },
    copilot: { eyebrow: "Field guide", title: "AI Copilot", subtitle: "Query authorized field history only.", question: "Question for the copilot", placeholder: "Ask about observations, species, or field notes…", ask: "Send", thinking: "Thinking…", sources: "Authorized sources", welcome: "I am here to explore your field history.", welcomeHint: "I will answer only from records you are authorized to access.", enterHint: "Enter to send · Shift + Enter for a new line", usageTitle: "Session usage", usageSubtitle: "Session activity and query summary", usageQueries: "queries", usageQueriesHint: "Questions sent", usageTokens: "tokens processed", usageTokensHint: "Processing volume", usageLastQuery: "last query", usageLastQueryHint: "Last response received", usageSecurityNotice: "Answers are generated exclusively from field records authorized for your accreditation level.", usageEmpty: "There are no recorded queries yet.", usageUnavailable: "Usage could not be loaded.", newConversation: "New chat", conversations: "Chat history", deleteConversation: "Delete chat", confirmDeleteTitle: "Delete conversation?", confirmDeleteMessage: "Do you want to delete the chat \"{{title}}\"? It will be archived from your query history.", confirmDeleteButton: "Delete", noConversations: "No previous chats" },
    chat: { sidebarTitle: "Communications", searchPlaceholder: "Search researcher or channel…", researchers: "Researchers", channels: "Field Channels", emptyChannels: "No active channels", selectPrompt: "Select a conversation", selectPromptDesc: "Choose a researcher or channel to send secure messages or invoke @copilot.", placeholder: "Type a message or use @copilot to query…", enterHint: "Enter to send · Shift + Enter for new line", copilotHint: "Mention @copilot to query authorized field records.", protectedChannel: "Secure & confidential channel", usageTitle: "Chat Copilot Usage", usageSubtitle: "Accumulated RAG processing metrics and tokens", queries: "total queries", queriesHint: "Queries answered by the copilot", tokens: "tokens consumed", tokensHint: "Total input and output tokens", lastQuery: "last interaction", lastQueryHint: "Timestamp of last copilot reply", securityNotice: "The copilot only answers with sightings authorized for all channel members.", createGroup: "Create group", createGroupTitle: "New Research Group", createGroupSubtitle: "Create a collaborative workspace to share sightings and query @copilot.", groupName: "Group name", groupNamePlaceholder: "E.g. Sierra Nevada Expedition", selectMembers: "Select participating researchers", membersCount: "{{count}} selected", createGroupSubmit: "Create Group", groupMemberCount: "{{count}} researchers", minMembersHint: "Select at least one colleague for the group.", viewMembers: "View members", messageOptions: "Message options", editMessage: "Edit", deleteMessage: "Delete", deletedMessage: "This message was deleted", editedMessage: "Edited message", authorizedSources: "Authorized sources", accessLevel: "Access level", groupMembersTitle: "Group members", activeResearchers: "{{count}} active researchers", searchColleague: "Search colleague by name or role…", selectResearcher: "Select {{name}}", level: "Level {{level}}", copilotName: "Bioma Copilot" },
    profile: { title: "Research profile", signedIn: "Signed in", level: "Level {{level}}", logout: "Sign out", adminDescription: "Manage the system prompt and its version history.", openAdmin: "Manage prompts" },
    adminPrompts: { restrictedTitle: "Restricted administration", restrictedDescription: "Only an administrator account can manage prompt versions.", title: "Copilot prompts", description: "Creating a version activates it; you can restore an earlier version without losing traceability.", scope: "Scope", field: "Field copilot", chat: "Messages copilot", greeting: "Greetings", placeholder: "Write a new version…", save: "Save and activate version", history: "Verifiable history", active: "Active", createdBy: "Created by {{name}}", restore: "Restore" },



  } },
};

void i18n.use(initReactI18next).init({ resources, lng: "es", fallbackLng: "es", interpolation: { escapeValue: false } });
export default i18n;
